# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "lib" << "tests"
  t.pattern = "tests/**/*_test.rb"
  t.warning = false
end

desc "Run the test suite with a coverage report (writes coverage/)"
task :coverage do
  ENV["COVERAGE"] = "1"
  Rake::Task["test"].invoke
end

task default: :test
